<?php

namespace ProductsBundle\Repository;

/**
 * BiddingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiddingRepository extends \Doctrine\ORM\EntityRepository
{
}
