<?php

namespace ProductsBundle\Repository;

/**
 * history_biddingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class history_biddingRepository extends \Doctrine\ORM\EntityRepository
{
}
