<?php

namespace ProductsBundle\Repository;

/**
 * RatesUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatesUserRepository extends \Doctrine\ORM\EntityRepository
{
}
