<?php

namespace ProductsBundle\Repository;

/**
 * RatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatesRepository extends \Doctrine\ORM\EntityRepository
{
}
